<a href="https://colab.research.google.com/github/akshay2077/Colab3012/blob/main/332_Practical3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array3 = np.loadtxt('/content/salaryexp.csv',delimiter=',',dtype=str,skiprows=1)
print(array3)
sal=[]
exp=[]
for i in array3:
  sal.append(int(i[1]))
  exp.append(int(i[2]))
print(sal)
print(exp)

#converting list to array
arr_sal = np.array(sal)
arr_exp = np.array(exp)

#displaying array
print("Array1:",arr_sal)
print("Array2:",arr_exp)

#standard deviation salary
print(np.std(sal))

#standard deviation exp
print(np.std(exp))

#minimum salary
print(np.min(sal))

#minimum exp
print(np.min(exp))

#median salary
print(np.median(sal))

#median exp
print(np.median(exp))

#addition of salary and exp
array1 = np.array(sal)
array2 = np.array(exp)
print(array1+array2)

#multiplication of salary and exp
array1 = np.array(sal)
array2 = np.array(exp)
print(array1*array2)

# horizontal stacking in numpy
array1 = np.array(sal)
array2 = np.array(exp)
output_array = np.hstack((array1,array2))
print(output_array)

#vertical stacking in numpy
array1 = np.array(sal)
array2 = np.array(exp)
output_array = np.vstack((array1,array2))
print(output_array)

#copying in numpy
array1 = np.array(sal)
x = array1.copy()
array1[0] = 50000
print(x)
print(array1)

#view in numpy
array1 = np.array(exp)
x = array1.view()
print(x)
array1[0] = 13
print(array1)

# searching in array
a = np.array(sal)
b = np.array(exp)
print(np.where(a==b))

#sorting in array
a = np.array(sal)
print(np.sort(a))

[['Arjun' '26000' '8' 'tcs' 'Male']
 ['Vijay' '30000' '7' 'wipro' 'Male']
 ['Rajni' '32000' '10' 'tcs' 'Female']
 ['Girish' '45000' '9' 'accenture' 'Male']
 ['Radha' '42000' '12' 'cognizant' 'Female']
 ['Mayur' '47000' '10' 'Infosys' 'Male']
 ['Ujjwal' '52000' '11' 'hcl' 'Male']
 ['Nihar' '48000' '10' 'wipro' 'Male']]
[26000, 30000, 32000, 45000, 42000, 47000, 52000, 48000]
[8, 7, 10, 9, 12, 10, 11, 10]
Array1: [26000 30000 32000 45000 42000 47000 52000 48000]
Array2: [ 8  7 10  9 12 10 11 10]
8982.62211161084
1.4947825928876748
26000
7
43500.0
10.0
[26008 30007 32010 45009 42012 47010 52011 48010]
[208000 210000 320000 405000 504000 470000 572000 480000]
[26000 30000 32000 45000 42000 47000 52000 48000     8     7    10     9
    12    10    11    10]
[[26000 30000 32000 45000 42000 47000 52000 48000]
 [    8     7    10     9    12    10    11    10]]
[26000 30000 32000 45000 42000 47000 52000 48000]
[50000 30000 32000 45000 42000 47000 52000 48000]
[ 8  7 10  9 12 10 11 10]
[13  7 1