<a href="https://colab.research.google.com/github/akshay2077/Colab3012/blob/main/Copy_of_Copy_of_Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.vstack((arr1,arr2))
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(np.sort(arr))

[1 2 3 4 5]


In [ ]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.hstack((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr = ([[1,2,3,4],[5,6,7,8]])
print(np.sort(arr))

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)

[1 3]


In [ ]:
import numpy as np
list1 = [x for x in range(0,101,2)]
a = np.array(list1)
print(a)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [ ]:
import numpy as np
list1 = [x for x in range(1,100,3)]
a = np.array(list1)
print(a)
print(type(list))
print(type(a))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]
<class 'type'>
<class 'numpy.ndarray'>


In [ ]:
b = np.arange(50,0,-1).reshape(5,10)
print(b)

[[50 49 48 47 46 45 44 43 42 41]
 [40 39 38 37 36 35 34 33 32 31]
 [30 29 28 27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14 13 12 11]
 [10  9  8  7  6  5  4  3  2  1]]


In [ ]:
b = np.arange(9,0,-1).reshape(3,3)
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6])
nparray=np.empty((3,3),int)
print(nparray)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
z = np.linspace(0,100,5)
print(z)

[  0.  25.  50.  75. 100.]


In [ ]:
a = np.linspace(1,50,5)
print(a)

[ 1.   13.25 25.5  37.75 50.  ]


In [ ]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,3,5,4])
print(np.where(a==b))


(array([0, 3]),)


In [ ]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,3,5,4])
print(np.where(a==4))
print(np.where(b==4))

(array([3]),)
(array([3]),)


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
x = np.where(arr%2==0)
print(x)

(array([ 1,  3,  5,  7,  9, 11, 13]),)


In [ ]:
import numpy as np
arr = ([1,2,3,4,5,6])
x = np.searchsorted(arr,5)
print(x)

4


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
x = np.searchsorted(arr,4,side='right')
print(x)

4


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
x = np.searchsorted(arr,1,side='right')
print(x)

1


In [ ]:
array1 = np.array([1,2,3,4,5,6,7,8,9])
#standard deviation
print(np.std(array1))
# minimun
print(np.min(array1))
# median
print(np.median(array1))
# mean
print(np.mean(array1))

# variance
print(np.var(array1))


2.581988897471611
1
5.0
5.0
6.666666666666667


In [ ]:
import numpy as np
array1 = np.array([1,2,3,4,5,6,7,0])
print(np.count_nonzero(array1))
print(np.nonzero(array1))
print(array1.size)


7
(array([0, 1, 2, 3, 4, 5, 6]),)
8


In [ ]:
import numpy as np
a = np.array([1.0,2.0,3.0,4.0])
b = np.array([2.0,2.0,2.0,2.0])
a * b
print(a*b)

[2. 4. 6. 8.]


In [ ]:
import numpy as np
a = np.array([1.0,2.0,3.0,4.0])
b = 2.0
a * b
print(a*b)

[2. 4. 6. 8.]


In [ ]:
import numpy as np
a = np.array([[0.0,1.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]])
b = np.array([1.0,2.0,3.0])
a + b
print(a+b)

[[ 1.  3.  6.]
 [ 5.  7.  9.]
 [ 8. 10. 12.]]


In [ ]:
import numpy as np
array3 = np.loadtxt('/content/salary.csv',delimiter=',',dtype=str,skiprows=1)
print(array3)
sal=[]
exp=[]
for i in array3:
  sal.append(int(i[1]))
  exp.append(int(i[2]))
print(sal)
print(exp)

#converting list to array
arr_sal = np.array(sal)
arr_exp = np.array(exp)

#displaying array
print("Array1:",arr_sal)
print("Array2:",arr_exp)

#standard deviation salary
print(np.std(sal))

#standard deviation exp
print(np.std(exp))

#minimum salary
print(np.min(sal))

#minimum exp
print(np.min(exp))

#median salary
print(np.median(sal))

#median exp
print(np.median(exp))

#addition of salary and exp
array1 = np.array(sal)
array2 = np.array(exp)
print(array1+array2)

#multiplication of salary and exp
array1 = np.array(sal)
array2 = np.array(exp)
print(array1*array2)


[['raj' '25000' '12']
 ['vijay' '20000' '8']
 ['kishor' '15000' '7']
 ['kiran' '18000' '8']
 ['sahil' '21000' '10']
 ['priyank' '30000' '5']
 ['ramesh' '28000' '6']]
[25000, 20000, 15000, 18000, 21000, 30000, 28000]
[12, 8, 7, 8, 10, 5, 6]
Array1: [25000 20000 15000 18000 21000 30000 28000]
Array2: [12  8  7  8 10  5  6]
5038.626311013828
2.2038926600773587
15000
5
21000.0
8.0
[25012 20008 15007 18008 21010 30005 28006]
[300000 160000 105000 144000 210000 150000 168000]
